In [42]:
include("./util.jl")
include("./parsers.jl")

getTunnels (generic function with 1 method)

In [43]:
env = Gurobi.Env()

Academic license - for non-commercial use only


Gurobi.Env(Ptr{Nothing} @0x00007fdfdca95c00)

In [98]:
topology = "B4"
cutoffs = [0.99]
iterations = 1
weibull = true
shape = 0.8
scale = 0.001
paths = "SMORE"
demand_num = 1
beta=0.99

0.99

In [99]:
y_vals = [[] for i=1:length(cutoffs) + 1]
x_vals = []

0-element Array{Any,1}

In [100]:
vals = zeros(length(cutoffs) + 1)
links, capacity, link_probs, nodes = readTopology(topology)
demand, flows = readDemand("$(topology)/demand", length(nodes), demand_num,
    matrix=true)
T, Tf, k = parsePaths("$(topology)/paths/$(paths)", links, flows)
push!(x_vals, length(links))

1-element Array{Any,1}:
 38

In [112]:
for d=1:length(demand)
    println(demand[d])
end

9.466804472
52.353326212
12.755747757
6.417379799
27.734892783
18.106391234
38.742817362000004
4.149067603000001
14.539530409000001
53.50111661
146.39510562200002
5.746500456
14.529689052
3.802235372
2.054526997
8.267221365
5.397156053
11.548465319
1.236754748
4.3339455959999995
15.947621566
43.637476963
0.962108663
0.439881936
0.683723823
0.32026648799999996
1.4866244830000002
0.970524917
2.076662826
0.222395144
0.779336774
2.86772588
7.846958338
11.618971663
5.705592223
33.889302937000004
4.461666802
17.95332315
13.520486713
28.930212574000002
3.098210608
10.857024194
39.95059683
109.316818286
261.468165541
137.90273873499999
710.056208235
199.570543942
433.92733568
283.28424300999995
606.15224461
64.91439734299999
227.478784273
837.05378521
2290.430276255
148.344126332
72.845611303
432.67848325799997
105.420953963
56.963910649999995
172.621540626
369.363764136
39.556112119
138.616033789
510.065482126
1395.692181049
37.740324653
18.532698855
110.07801139499999
30.938858579
14.4922251

In [101]:
include("./Algorithms/TEAVAR.jl")

TEAVAR (generic function with 1 method)

In [108]:
probabilities = weibullProbs(length(links), shape=shape, scale=.01)
cutoff = (sum(probabilities)/length(probabilities))^2
scenarios, scenario_probs = subScenariosRecursion(probabilities,
    cutoff)


(Any[[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0  …  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0  …  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0  …  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0  …  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0  …  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0  …  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0  …  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0  …  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0  …  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 

In [109]:
probabilities

38-element Array{Any,1}:
 0.026978561776755065 
 0.02156084381594179  
 0.010301050844885242 
 0.007191735247417416 
 0.0036773701356309337
 0.007210840012451051 
 0.0006467887980056543
 0.027970511081557962 
 0.005666767453640627 
 0.003278525786743426 
 0.006222509601624736 
 0.006856254966491738 
 0.024520660377320872 
 ⋮                    
 0.003753757110110824 
 0.0027631955020701606
 0.0031270652674347953
 0.012911897465817493 
 0.014639146509532753 
 0.0042589380587361595
 0.010904461145653513 
 0.05770860143966605  
 0.0006436059055837652
 0.0075635114401235316
 0.002492304208981177 
 0.0017110526519641283

In [ ]:
TEAVAR(env, links, capacity, flows, demand, beta, k,
    T, Tf, scenarios, scenario_probs, explain=true, verbose=true,
        utilization=true)